name: "build"
on:
  [push, workflow_dispatch]

jobs:
  build-ink:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - uses: engineerd/configurator@v0.0.8
      with:
        name: "inklecate"
        fromGitHubReleases: "true"
        repo: "inkle/ink"
        urlTemplate: "https://github.com/inkle/ink/releases/download/{{version}}/inklecate_linux.zip"
        version: "latest"
        token: ${{ secrets.GITHUB_TOKEN }}
        pathInArchive: "inklecate"
    - name: install, build ink, build website
      run: yarn && yarn ink && yarn build && yarn make-player && yarn dist
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
    